
// <auto-generated />
using Cirrus.Localisation;

namespace Cirrus.Module.CatchEmAll.DAL
{

	public class ResourceFileNameProvider : Cirrus.Localisation.Resource.ResourceFileNameProvider 
	{
	}


    internal class AlertMessages : Cirrus.Localisation.AlertMessages
    {
		
		public static ITranslationItem CatchEmAll_CannotDeleteFeedbackInGivenState { get; } = new TranslationItem("CatchEmAll_CannotDeleteFeedbackInGivenState", "AlertMessages");    
		public static ITranslationItem CatchEmAll_CategoryHasAssignedQueries { get; } = new TranslationItem("CatchEmAll_CategoryHasAssignedQueries", "AlertMessages");    
    }

        
    internal class DataObjects : Cirrus.Localisation.DataObjects
    {
		
		public static ITranslationItem CatchEmAll_AlternativeEmail { get; } = new TranslationItem("CatchEmAll_AlternativeEmail", "DataObjects");    
		public static ITranslationItem CatchEmAll_ArchivedSearchResult { get; } = new TranslationItem("CatchEmAll_ArchivedSearchResult", "DataObjects");    
		public static ITranslationItem CatchEmAll_ArchivedSearchResults { get; } = new TranslationItem("CatchEmAll_ArchivedSearchResults", "DataObjects");    
		public static ITranslationItem CatchEmAll_AutoFilterDeletedDuplicates { get; } = new TranslationItem("CatchEmAll_AutoFilterDeletedDuplicates", "DataObjects");    
		public static ITranslationItem CatchEmAll_AutoFilterDeletedDuplicatesDefault { get; } = new TranslationItem("CatchEmAll_AutoFilterDeletedDuplicatesDefault", "DataObjects");    
		public static ITranslationItem CatchEmAll_AverageFinalPrice { get; } = new TranslationItem("CatchEmAll_AverageFinalPrice", "DataObjects");    
		public static ITranslationItem CatchEmAll_BidPrice { get; } = new TranslationItem("CatchEmAll_BidPrice", "DataObjects");    
		public static ITranslationItem CatchEmAll_Categories { get; } = new TranslationItem("CatchEmAll_Categories", "DataObjects");    
		public static ITranslationItem CatchEmAll_Category { get; } = new TranslationItem("CatchEmAll_Category", "DataObjects");    
		public static ITranslationItem CatchEmAll_Closed { get; } = new TranslationItem("CatchEmAll_Closed", "DataObjects");    
		public static ITranslationItem CatchEmAll_Condition { get; } = new TranslationItem("CatchEmAll_Condition", "DataObjects");    
		public static ITranslationItem CatchEmAll_Created { get; } = new TranslationItem("CatchEmAll_Created", "DataObjects");    
		public static ITranslationItem CatchEmAll_CronExpression { get; } = new TranslationItem("CatchEmAll_CronExpression", "DataObjects");    
		public static ITranslationItem CatchEmAll_Description { get; } = new TranslationItem("CatchEmAll_Description", "DataObjects");    
		public static ITranslationItem CatchEmAll_DesiredPrice { get; } = new TranslationItem("CatchEmAll_DesiredPrice", "DataObjects");    
		public static ITranslationItem CatchEmAll_Email { get; } = new TranslationItem("CatchEmAll_Email", "DataObjects");    
		public static ITranslationItem CatchEmAll_EnableEmailNotification { get; } = new TranslationItem("CatchEmAll_EnableEmailNotification", "DataObjects");    
		public static ITranslationItem CatchEmAll_EnableIftttNotification { get; } = new TranslationItem("CatchEmAll_EnableIftttNotification", "DataObjects");    
		public static ITranslationItem CatchEmAll_EnableNotifications { get; } = new TranslationItem("CatchEmAll_EnableNotifications", "DataObjects");    
		public static ITranslationItem CatchEmAll_EnableNotificationsDefault { get; } = new TranslationItem("CatchEmAll_EnableNotificationsDefault", "DataObjects");    
		public static ITranslationItem CatchEmAll_End { get; } = new TranslationItem("CatchEmAll_End", "DataObjects");    
		public static ITranslationItem CatchEmAll_Ended { get; } = new TranslationItem("CatchEmAll_Ended", "DataObjects");    
		public static ITranslationItem CatchEmAll_Ends { get; } = new TranslationItem("CatchEmAll_Ends", "DataObjects");    
		public static ITranslationItem CatchEmAll_Execution { get; } = new TranslationItem("CatchEmAll_Execution", "DataObjects");    
		public static ITranslationItem CatchEmAll_ExecutionCount { get; } = new TranslationItem("CatchEmAll_ExecutionCount", "DataObjects");    
		public static ITranslationItem CatchEmAll_Executions { get; } = new TranslationItem("CatchEmAll_Executions", "DataObjects");    
		public static ITranslationItem CatchEmAll_ExecutionType { get; } = new TranslationItem("CatchEmAll_ExecutionType", "DataObjects");    
		public static ITranslationItem CatchEmAll_ExternalData { get; } = new TranslationItem("CatchEmAll_ExternalData", "DataObjects");    
		public static ITranslationItem CatchEmAll_ExternalId { get; } = new TranslationItem("CatchEmAll_ExternalId", "DataObjects");    
		public static ITranslationItem CatchEmAll_ExternalUrl { get; } = new TranslationItem("CatchEmAll_ExternalUrl", "DataObjects");    
		public static ITranslationItem CatchEmAll_Feedback { get; } = new TranslationItem("CatchEmAll_Feedback", "DataObjects");    
		public static ITranslationItem CatchEmAll_Feedbacks { get; } = new TranslationItem("CatchEmAll_Feedbacks", "DataObjects");    
		public static ITranslationItem CatchEmAll_FinalPrice { get; } = new TranslationItem("CatchEmAll_FinalPrice", "DataObjects");    
		public static ITranslationItem CatchEmAll_Id { get; } = new TranslationItem("CatchEmAll_Id", "DataObjects");    
		public static ITranslationItem CatchEmAll_IftttMakerEventName { get; } = new TranslationItem("CatchEmAll_IftttMakerEventName", "DataObjects");    
		public static ITranslationItem CatchEmAll_IftttMakerKey { get; } = new TranslationItem("CatchEmAll_IftttMakerKey", "DataObjects");    
		public static ITranslationItem CatchEmAll_IsDefault { get; } = new TranslationItem("CatchEmAll_IsDefault", "DataObjects");    
		public static ITranslationItem CatchEmAll_IsEnabled { get; } = new TranslationItem("CatchEmAll_IsEnabled", "DataObjects");    
		public static ITranslationItem CatchEmAll_IsUserInitiated { get; } = new TranslationItem("CatchEmAll_IsUserInitiated", "DataObjects");    
		public static ITranslationItem CatchEmAll_LastUpdated { get; } = new TranslationItem("CatchEmAll_LastUpdated", "DataObjects");    
		public static ITranslationItem CatchEmAll_Marker { get; } = new TranslationItem("CatchEmAll_Marker", "DataObjects");    
		public static ITranslationItem CatchEmAll_Message { get; } = new TranslationItem("CatchEmAll_Message", "DataObjects");    
		public static ITranslationItem CatchEmAll_Miscellaneous { get; } = new TranslationItem("CatchEmAll_Miscellaneous", "DataObjects");    
		public static ITranslationItem CatchEmAll_Name { get; } = new TranslationItem("CatchEmAll_Name", "DataObjects");    
		public static ITranslationItem CatchEmAll_NotificationMode { get; } = new TranslationItem("CatchEmAll_NotificationMode", "DataObjects");    
		public static ITranslationItem CatchEmAll_NotificationsEnabled { get; } = new TranslationItem("CatchEmAll_NotificationsEnabled", "DataObjects");    
		public static ITranslationItem CatchEmAll_Number { get; } = new TranslationItem("CatchEmAll_Number", "DataObjects");    
		public static ITranslationItem CatchEmAll_NumberOfOpenResults { get; } = new TranslationItem("CatchEmAll_NumberOfOpenResults", "DataObjects");    
		public static ITranslationItem CatchEmAll_NumberOfQueries { get; } = new TranslationItem("CatchEmAll_NumberOfQueries", "DataObjects");    
		public static ITranslationItem CatchEmAll_NumberOfResults { get; } = new TranslationItem("CatchEmAll_NumberOfResults", "DataObjects");    
		public static ITranslationItem CatchEmAll_PurchasePrice { get; } = new TranslationItem("CatchEmAll_PurchasePrice", "DataObjects");    
		public static ITranslationItem CatchEmAll_Schedule { get; } = new TranslationItem("CatchEmAll_Schedule", "DataObjects");    
		public static ITranslationItem CatchEmAll_Schedules { get; } = new TranslationItem("CatchEmAll_Schedules", "DataObjects");    
		public static ITranslationItem CatchEmAll_SearchQueries { get; } = new TranslationItem("CatchEmAll_SearchQueries", "DataObjects");    
		public static ITranslationItem CatchEmAll_SearchQuery { get; } = new TranslationItem("CatchEmAll_SearchQuery", "DataObjects");    
		public static ITranslationItem CatchEmAll_SearchResult { get; } = new TranslationItem("CatchEmAll_SearchResult", "DataObjects");    
		public static ITranslationItem CatchEmAll_SearchResults { get; } = new TranslationItem("CatchEmAll_SearchResults", "DataObjects");    
		public static ITranslationItem CatchEmAll_Settings { get; } = new TranslationItem("CatchEmAll_Settings", "DataObjects");    
		public static ITranslationItem CatchEmAll_SettingsQuery { get; } = new TranslationItem("CatchEmAll_SettingsQuery", "DataObjects");    
		public static ITranslationItem CatchEmAll_SettingsUser { get; } = new TranslationItem("CatchEmAll_SettingsUser", "DataObjects");    
		public static ITranslationItem CatchEmAll_Sold { get; } = new TranslationItem("CatchEmAll_Sold", "DataObjects");    
		public static ITranslationItem CatchEmAll_Start { get; } = new TranslationItem("CatchEmAll_Start", "DataObjects");    
		public static ITranslationItem CatchEmAll_Status { get; } = new TranslationItem("CatchEmAll_Status", "DataObjects");    
		public static ITranslationItem CatchEmAll_Successful { get; } = new TranslationItem("CatchEmAll_Successful", "DataObjects");    
		public static ITranslationItem CatchEmAll_Tags { get; } = new TranslationItem("CatchEmAll_Tags", "DataObjects");    
		public static ITranslationItem CatchEmAll_UpdateIntervalInMinutes { get; } = new TranslationItem("CatchEmAll_UpdateIntervalInMinutes", "DataObjects");    
		public static ITranslationItem CatchEmAll_UseDescription { get; } = new TranslationItem("CatchEmAll_UseDescription", "DataObjects");    
		public static ITranslationItem CatchEmAll_Username { get; } = new TranslationItem("CatchEmAll_Username", "DataObjects");    
		public static ITranslationItem CatchEmAll_WithAllTheseWords { get; } = new TranslationItem("CatchEmAll_WithAllTheseWords", "DataObjects");    
		public static ITranslationItem CatchEmAll_WithExactlyTheseWords { get; } = new TranslationItem("CatchEmAll_WithExactlyTheseWords", "DataObjects");    
		public static ITranslationItem CatchEmAll_WithNoneOfTheseWords { get; } = new TranslationItem("CatchEmAll_WithNoneOfTheseWords", "DataObjects");    
		public static ITranslationItem CatchEmAll_WithOneOfTheseWords { get; } = new TranslationItem("CatchEmAll_WithOneOfTheseWords", "DataObjects");    
    }

        
    internal class DisplayActions : Cirrus.Localisation.DisplayActions
    {
		
		public static IDisplayAction CatchEmAll_EditQuery { get; } = new DisplayAction("CatchEmAll_EditQuery");     
		public static IDisplayAction CatchEmAll_ImportExisting { get; } = new DisplayAction("CatchEmAll_ImportExisting");     
		public static IDisplayAction CatchEmAll_ShowAllExecutions { get; } = new DisplayAction("CatchEmAll_ShowAllExecutions");     
		public static IDisplayAction CatchEmAll_ShowArchive { get; } = new DisplayAction("CatchEmAll_ShowArchive");     
		public static IDisplayAction CatchEmAll_ShowFailedExecutions { get; } = new DisplayAction("CatchEmAll_ShowFailedExecutions");     
		public static IDisplayAction CatchEmAll_ShowRunningExecutions { get; } = new DisplayAction("CatchEmAll_ShowRunningExecutions");     
		public static IDisplayAction CatchEmAll_UpdateFromSource { get; } = new DisplayAction("CatchEmAll_UpdateFromSource");     
    }

        
    internal class Navigation : Cirrus.Localisation.Navigation
    {
		
		public static ITranslationItem CatchEmAll_CatchEmAll { get; } = new TranslationItem("CatchEmAll_CatchEmAll", "Navigation");    
		public static ITranslationItem CatchEmAll_CatchEmAllAdmin { get; } = new TranslationItem("CatchEmAll_CatchEmAllAdmin", "Navigation");    
		public static ITranslationItem CatchEmAll_Categories { get; } = new TranslationItem("CatchEmAll_Categories", "Navigation");    
		public static ITranslationItem CatchEmAll_Feedback { get; } = new TranslationItem("CatchEmAll_Feedback", "Navigation");    
		public static ITranslationItem CatchEmAll_QueryExecution { get; } = new TranslationItem("CatchEmAll_QueryExecution", "Navigation");    
		public static ITranslationItem CatchEmAll_Schedules { get; } = new TranslationItem("CatchEmAll_Schedules", "Navigation");    
		public static ITranslationItem CatchEmAll_SearchQueries { get; } = new TranslationItem("CatchEmAll_SearchQueries", "Navigation");    
		public static ITranslationItem CatchEmAll_SearchQueriesByCategory { get; } = new TranslationItem("CatchEmAll_SearchQueriesByCategory", "Navigation");    
		public static ITranslationItem CatchEmAll_Settings { get; } = new TranslationItem("CatchEmAll_Settings", "Navigation");    
    }

        
    internal class UiComponents : Cirrus.Localisation.UiComponents
    {
		
		public static ITranslationItem CatchEmAll_ExternalResultDataComponentDescription { get; } = new TranslationItem("CatchEmAll_ExternalResultDataComponentDescription", "UiComponents");    
		public static ITranslationItem CatchEmAll_ExternalResultDataComponentName { get; } = new TranslationItem("CatchEmAll_ExternalResultDataComponentName", "UiComponents");    
		public static ITranslationItem CatchEmAll_QueryExecutionStatisticsComponentDescription { get; } = new TranslationItem("CatchEmAll_QueryExecutionStatisticsComponentDescription", "UiComponents");    
		public static ITranslationItem CatchEmAll_QueryExecutionStatisticsComponentName { get; } = new TranslationItem("CatchEmAll_QueryExecutionStatisticsComponentName", "UiComponents");    
		public static ITranslationItem CatchEmAll_ScheduleStatisticsComponentDescription { get; } = new TranslationItem("CatchEmAll_ScheduleStatisticsComponentDescription", "UiComponents");    
		public static ITranslationItem CatchEmAll_ScheduleStatisticsComponentName { get; } = new TranslationItem("CatchEmAll_ScheduleStatisticsComponentName", "UiComponents");    
    }

        
    internal class WebApplication : Cirrus.Localisation.WebApplication
    {
		
		public static ITranslationItem CatchEmAll_Categories { get; } = new TranslationItem("CatchEmAll_Categories", "WebApplication");    
		public static ITranslationItem CatchEmAll_OpenExternalUrl { get; } = new TranslationItem("CatchEmAll_OpenExternalUrl", "WebApplication");    
		public static ITranslationItem CatchEmAll_QueryExecutionsPastDay { get; } = new TranslationItem("CatchEmAll_QueryExecutionsPastDay", "WebApplication");    
		public static ITranslationItem CatchEmAll_QueryExecutionsPastHour { get; } = new TranslationItem("CatchEmAll_QueryExecutionsPastHour", "WebApplication");    
		public static ITranslationItem CatchEmAll_QueryExecutionsPastWeek { get; } = new TranslationItem("CatchEmAll_QueryExecutionsPastWeek", "WebApplication");    
		public static ITranslationItem CatchEmAll_Schedules { get; } = new TranslationItem("CatchEmAll_Schedules", "WebApplication");    
		public static ITranslationItem CatchEmAll_SearchQueries { get; } = new TranslationItem("CatchEmAll_SearchQueries", "WebApplication");    
		public static ITranslationItem CatchEmAll_SearchResults { get; } = new TranslationItem("CatchEmAll_SearchResults", "WebApplication");    
    }

}
#pragma warning restore
