// <auto-generated />
namespace Cirrus.Module.CatchEmAll.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewQueryOptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewQueryOptions));
        
        string IMigrationMetadata.Id
        {
            get { return "201707141155049_NewQueryOptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
