// <auto-generated />
namespace Cirrus.Module.CatchEmAll.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewFlagsOnResult : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFlagsOnResult));
        
        string IMigrationMetadata.Id
        {
            get { return "201708291024425_NewFlagsOnResult"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
